runtime: python311
entrypoint: gunicorn -b :$PORT examapp.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "examapp.settings_cloud"

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto

runtime_config:
  python_version: 3.11
