# Generated by Django 4.2.2 on 2023-06-17 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_questions', '0004_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
