# Generated by Django 4.2.2 on 2023-06-21 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_questions', '0008_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
