# Generated by Django 4.2.2 on 2023-06-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_questions', '0010_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
